### ISSUE TITLE
Bug: 出现异常

### ISSUE THREAD

**Issue by xixijiang2005** [kanbereina/nonebot-plugin-llob-master#5]
### Windows 版本

win11 24h2

### Python 版本

3.11.5

### LLOB-Master 版本

1.1.1

### 描述问题

一直出现qqnt版本获取失败
11-03 01:48:08 [WARNING] nonebot_plugin_llob_master | 请不要在任何影响力较大的简中互联网平台, 发布和讨论任何与LLOB、本插件存在相关性的信息!
11-03 01:48:08 [WARNING] nonebot_plugin_llob_master | 文件实际不存在!
11-03 01:48:08 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\20882\Desktop\squad\squadbot\.venv\Lib\site-packages\nonebot_plugin_llob_master\utils\ntqq\ntqq_update_main.py", line 41, in get_version
    raise FileNotFoundError("文件实际不存在!")
FileNotFoundError: 文件实际不存在!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\20882\Desktop\squad\squadbot\.venv\Lib\site-packages\starlette\routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Program Files\Python311\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20882\Desktop\squad\squadbot\.venv\Lib\site-packages\nonebot\drivers\fastapi.py", line 155, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\20882\Desktop\squad\squadbot\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 66, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\20882\Desktop\squad\squadbot\.venv\Lib\site-packages\nonebot\internal\driver\_lifespan.py", line 55, in _run_lifespan_func
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\20882\Desktop\squad\squadbot\.venv\Lib\site-packages\nonebot_plugin_llob_master\__main__.py", line 148, in start
    ntqq_path = await ntqq_update_checker()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20882\Desktop\squad\squadbot\.venv\Lib\site-packages\nonebot_plugin_llob_master\utils\ntqq\ntqq_update_main.py", line 81, in ntqq_update_checker
    ntqq_version = NTQQUpdater.get_version(ntqq_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20882\Desktop\squad\squadbot\.venv\Lib\site-packages\nonebot_plugin_llob_master\utils\ntqq\ntqq_update_main.py", line 55, in get_version
    raise RuntimeError("NTQQ版本获取失败!")
RuntimeError: NTQQ版本获取失败!

11-03 01:48:08 [ERROR] uvicorn | Application startup failed. Exiting.

### 复现步骤

正常安装，设置了QQnt的路径

### 期望的结果

怎样才能正常运行

### 截图或日志

![屏幕截图 2024-11-03 015548](https://github.com/user-attachments/assets/33a439d4-f3e8-452a-8180-da620827ae9f)
![屏幕截图 2024-11-03 015658](https://github.com/user-attachments/assets/ed637b1f-87dc-4791-a192-d268d021eaed)

**Comment by kanbereina** [comment]
新版本QQ项目路径已更改，因学业精力有限，不会继续进行维护。
